#!/usr/bin/env python3
"""Skill template sidecar schema + redaction guard (Wave 4+ machine-template B-1).

Implements the §3 schema spec (Owner accepted "B all default" 2026-05-04):

- Q1 sidecar format: JSON (defends int/str auto-typing PR-5fg/5h bug class)
- Q4 schema versioning: contract version field `skill_template_schema: 1`
- Q6 audit_mode_required: optional metadata; illegal value -> violation, legal
  value -> silent (Finding D-a removed the blanket advisory warn that fired for
  every skill + failed --strict pack-wide)

Schema sidecar lives at `skills/<name>/skill.template.json`. SKILL.md
frontmatter remains canonical-fixed `name` + `description` only per
GUIDE §1; sidecar holds the rest (boundary class, audit mode, fixtures
metadata, etc.).

API:
    assert_safe_skill_template(record: dict) -> None  # raise SkillTemplateSchemaError
    check_skill_template(record: dict) -> SkillTemplateSchemaResult

No third-party dependencies; stdlib only.
"""

from __future__ import annotations

import posixpath
import re
from dataclasses import dataclass, field
from typing import Any, Mapping


# ===== Schema constants =====

SCHEMA_VERSION_ACCEPTED: frozenset[int] = frozenset({1})
DEFAULT_SCHEMA_VERSION: int = 1

# §3.1 metadata
SKILL_NAME_RE = re.compile(r"^aqg-[a-z0-9][a-z0-9-]{0,40}\Z")  # D4: \Z (not $) — $ matches before a trailing \n
ALLOWED_BOUNDARY_CLASS: frozenset[str] = frozenset({
    "read-only", "writes-evidence", "writes-code",
})
ALLOWED_AUDIT_MODE: frozenset[str] = frozenset({
    # Aligned to audit-mcp tiers (Owner 2026-06-04): fast / standard / deep.
    # Legacy {single, two, three} retired (single→standard, two→standard, three→deep).
    "fast", "standard", "deep", "none",
})

# §3.2 cli_contract — exit-code map (per ADR §3.2 + GUIDE §1.4)
EXPECTED_EXIT_CODES: frozenset[int] = frozenset({0, 1, 2, 3, 70})

ALLOWED_OUTPUT_SHAPES: frozenset[str] = frozenset({
    "markdown_table", "json", "ledger_block", "multi_section_report",
})

# §3.4 fixture cases[] — match the existing tests/behavior/fixtures/triggers.yaml
# convention which uses snake_case style values (description_based /
# explicit_invocation). Earlier schema drafted kebab values; corrected here so
# validator's mix-rule check actually matches the fixture file.
ALLOWED_FIXTURE_STYLE: frozenset[str] = frozenset({
    "description_based", "explicit_invocation",
})
CASE_ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]{0,79}\Z")  # D4: \Z (not $) — $ matches before a trailing \n

# Required top-level sidecar fields (§3.1-§3.5 collected)
REQUIRED_TOP_LEVEL: frozenset[str] = frozenset({
    "skill_template_schema",  # Q4 default: contract version
    "name",
    "description",
    "boundary_class",
    "trigger_grammar",
    "entry_script",
    "cli_contract",
    "output_shape",
    "reads_paths",
    "writes_paths",
    "forbidden_paths",
    "aqg_agent_gating",
    "owner_only_actions",
    "cases",
    "self_test_entrypoint",
    "fixed_before_next_task_required_when_findings",  # echoes ADR invariant 4
    "numeric_values_quoted",
})

# Optional fields (§3.1 + §6 deferred fields tagged provisional)
OPTIONAL_TOP_LEVEL: frozenset[str] = frozenset({
    "_doc",  # documentation note for sample manifests; ignored by validator
    "version",  # provisional pending Q4 (we ship Q4 default = include)
    "primary_trigger_keywords",
    "audit_mode_required",  # Q6 advisory v1
    # SKILL.md-from-source overlay (spec 2026-05-31 §3/§4): the migration flag +
    # per-host anchor→replacement overrides. The wrapper-overlay core
    # (_aqg_wrapper_overlay.build_wrapper) validates host_overrides SHAPE +
    # anchor semantics at regen time; here we type-check the SIDECAR shape so a
    # malformed flag/override is a schema violation, not a silent pass.
    "wrapper_generated",  # bool: this skill's Claude wrapper is generated by regen
    "host_overrides",  # {"claude": [{"anchor": str, "replacement": str}, ...]}
})

ALLOWED_TOP_LEVEL: frozenset[str] = REQUIRED_TOP_LEVEL | OPTIONAL_TOP_LEVEL


@dataclass(frozen=True)
class SkillTemplateSchemaResult:
    """is_safe = no errors; warnings is non-blocking advisory list (Q6 advisory)."""
    is_safe: bool
    violations: tuple[str, ...] = field(default_factory=tuple)
    warnings: tuple[str, ...] = field(default_factory=tuple)


class SkillTemplateSchemaError(Exception):
    def __init__(self, violations: list[str]):
        self.violations = tuple(violations)
        super().__init__(self._fmt())

    def _fmt(self) -> str:
        if not self.violations:
            return "skill template schema violation (no detail)"
        lines = [f"skill template schema violation ({len(self.violations)} issue(s)):"]
        for v in self.violations:
            lines.append(f"  - {v}")
        return "\n".join(lines)


# ===== Helpers =====


def _is_strict_int(v: Any) -> bool:
    return isinstance(v, int) and not isinstance(v, bool)


def _nonblank_str(v: Any) -> bool:
    """True iff v is a str with non-whitespace content.

    D3: the old `not v` check passed a whitespace-only string (`" "` is truthy),
    so blank values slipped past every "non-empty str" gate.
    """
    return isinstance(v, str) and bool(v.strip())


def _has_surrogate(s: str) -> bool:
    """True if *s* contains a UTF-16 surrogate code point (U+D800–U+DFFF).

    f1 (verify-round): a lone surrogate is legal in JSON (it decodes to a Python
    str) and passes `_nonblank_str`, then crashes the generator when an output
    file is written as UTF-8 — `UnicodeEncodeError`, because utf-8 cannot encode
    a surrogate. After json.loads a *valid* surrogate PAIR is already folded into
    one astral char, so any surrogate code point that remains is a LONE one. We
    test ord() membership rather than embed a surrogate in a regex literal so
    this module's own source stays pure ASCII.
    """
    return any(0xD800 <= ord(ch) <= 0xDFFF for ch in s)


def _surrogate_safe(msg: str) -> str:
    """Escape every UTF-16 surrogate code point in *msg* to an ASCII `\\udXXX`
    sequence (all other characters pass through unchanged). check_skill_template
    runs EVERY returned violation/warning string through this as a final pass.

    Rationale (round-2 verify, gpt-5.5 BLOCKING): a sidecar-derived value
    interpolated raw into a violation message — the same-skill pin diagnostics
    embed `name` / `expected_name` inside `skills/{name}/`, and the recursive
    surrogate scan embeds a key in its path prefix — would otherwise carry a lone
    surrogate. When the caller prints that violation to a strict-encoding stderr
    it raises UnicodeEncodeError: the very crash class the surrogate scan exists
    to prevent. Sanitizing at ONE choke point is robust to every current and
    future message, where hand-escaping each interpolation site is not (round-1
    fixed only the scan's own path and still left the pin diagnostics open)."""
    if not _has_surrogate(msg):
        return msg
    return "".join(
        f"\\u{ord(c):04x}" if 0xD800 <= ord(c) <= 0xDFFF else c for c in msg
    )


def _check_no_surrogates(name: str, value: Any, violations: list[str]) -> None:
    """Recursively reject lone UTF-16 surrogates in every sidecar string — both
    object keys and values. A single choke point so a string field added later
    cannot silently reintroduce the f1 generator crash. Non-str leaves (int /
    bool / None / float) are skipped; the structure is the already-parsed JSON
    record, so this is a bounded linear walk. A raw key may enter the path prefix
    here; the key-rejection message shows it via !r (ASCII) and check_skill_
    template's final _surrogate_safe pass guarantees every returned string is
    encodable regardless of which message produced it."""
    if isinstance(value, str):
        if _has_surrogate(value):
            violations.append(
                f"{name}: must not contain UTF-16 surrogate code points "
                f"(U+D800–U+DFFF)"
            )
    elif isinstance(value, Mapping):
        for k, v in value.items():
            if isinstance(k, str) and _has_surrogate(k):
                violations.append(
                    f"{name}: object key {k!r} must not contain UTF-16 "
                    f"surrogate code points (U+D800–U+DFFF)"
                )
            _check_no_surrogates(f"{name}.{k}", v, violations)
    elif isinstance(value, list):
        for i, item in enumerate(value):
            _check_no_surrogates(f"{name}[{i}]", item, violations)


# D5: a project-relative path must not smuggle control chars / NUL or a Windows
# drive prefix (the old _check_path_list rejected `\\` and `..` but not these).
_PATH_CONTROL_RE = re.compile(r"[\x00-\x1f\x7f]")  # NUL + C0 controls + DEL
_DRIVE_RE = re.compile(r"^[A-Za-z]:")


def _rel_path_violation(name: str, value: Any) -> str | None:
    """Return a violation message if *value* is not a safe project-relative POSIX
    path, else None. Centralizes the path rules so every path field (list items,
    entry_script, self_test_entrypoint, skill_file_ref) is checked identically."""
    if not _nonblank_str(value):
        return f"{name}: must be non-empty str"
    if _PATH_CONTROL_RE.search(value):
        return f"{name}: must not contain control characters"
    if (value.startswith("/") or value.startswith("~") or "\\" in value
            or ".." in value.split("/") or _DRIVE_RE.match(value)):
        return (
            f"{name}: must be project-relative POSIX path "
            f"(no leading /, no ~, no .., no \\, no drive letter)"
        )
    return None


# f2 (verify-round): entry_script / self_test_entrypoint / each case's
# skill_file_ref are interpolated into generated shell (`python3 "$aqg_root/<p>"`)
# and into generated Python. _rel_path_violation blocks traversal but NOT shell
# metacharacters ('"', '$', '`', ';', space, glob chars), so a schema-valid path
# like `skills/x/scripts/a";rm -rf ~ #.py` would close the double-quote in the
# How-To-Run block and append a command. These three fields are REAL, resolvable
# script/skill paths, so a strict POSIX-path charset is correct here. The
# reads_paths / writes_paths / forbidden_paths fields stay on the looser
# _rel_path_violation: they are DOCUMENTATION paths (one shipped sidecar
# legitimately reads `${XDG_DATA_HOME:-$HOME/.aqg}/.../<project_id>/events.jsonl`)
# and are never shell-interpolated.
_EXEC_PATH_CHARSET_RE = re.compile(r"^[A-Za-z0-9._/-]+\Z")


def _exec_path_violation(name: str, value: Any) -> str | None:
    """_rel_path_violation PLUS a strict shell-safe charset, for path fields that
    flow into generated shell/Python. Returns a violation message or None."""
    base = _rel_path_violation(name, value)
    if base:
        return base
    if not _EXEC_PATH_CHARSET_RE.match(value):
        return (
            f"{name}: must contain only [A-Za-z0-9._/-] "
            f"(no spaces or shell metacharacters), got {value!r}"
        )
    return None


def _check_enum(name: str, value: Any, allowed: "frozenset[str]", violations: list[str]) -> None:
    """D10: guard isinstance(str) before the `value not in frozenset` membership
    test — a list/dict value is unhashable, so `in` raises TypeError (a traceback)
    instead of producing a clean violation."""
    if value is None:
        return
    if not isinstance(value, str) or value not in allowed:
        violations.append(f"{name}: must be one of {sorted(allowed)}, got {value!r}")


def _canon_rel(p: str) -> str:
    """Canonicalize a project-relative POSIX path for prefix (D7) + overlap (D12)
    comparison: collapse leading './', repeated '//', interior '.', and trailing
    '/' so 'src', 'src/', './src', and 'a//b' compare by their true path.

    Round-2 verify (gpt-5.5 + gemini, convergent): the earlier hand-rolled
    _norm_rel under-normalized (`a//b`, interior `.`, `./skills/<other>/`),
    letting both the D7 same-skill pin and the D12 overlap be bypassed by an
    alternate spelling. posixpath.normpath canonicalizes all of these. Callers
    run _rel_path_violation FIRST, so any '..' is already rejected before
    normpath could collapse it."""
    return posixpath.normpath(p)


def _paths_overlap(a: str, b: str) -> bool:
    """True if canonical relative paths *a* and *b* are equal OR one is an
    ancestor of the other. A forbidden `secrets/` therefore overlaps a read of
    `secrets/prod.env`. The trailing '/' boundary avoids 's' matching 'src'."""
    a, b = _canon_rel(a), _canon_rel(b)
    return a == b or a.startswith(b + "/") or b.startswith(a + "/")


def _check_path_list(name: str, value: Any, violations: list[str]) -> None:
    """list of project-relative path strings. Empty list OK."""
    if not isinstance(value, list):
        violations.append(f"{name}: must be list, got {type(value).__name__}")
        return
    for i, p in enumerate(value):
        pv = _rel_path_violation(f"{name}[{i}]", p)
        if pv:
            violations.append(pv)


def _check_str_list(name: str, value: Any, violations: list[str], *, min_items: int = 0) -> None:
    if not isinstance(value, list):
        violations.append(f"{name}: must be list, got {type(value).__name__}")
        return
    if len(value) < min_items:
        violations.append(
            f"{name}: must have at least {min_items} items, got {len(value)}"
        )
    for i, item in enumerate(value):
        if not _nonblank_str(item):
            violations.append(f"{name}[{i}]: must be non-empty str")


def _check_cli_contract(value: Any, violations: list[str]) -> None:
    """cli_contract = mapping of int exit code → str description.
    Must include all EXPECTED_EXIT_CODES at minimum."""
    if not isinstance(value, dict):
        violations.append(
            f"cli_contract: must be mapping, got {type(value).__name__}"
        )
        return
    declared_codes: set[int] = set()
    for k, v in value.items():
        # JSON mappings have str keys; allow either int or str-of-int
        if isinstance(k, int):
            declared_codes.add(k)
        elif isinstance(k, str) and k.lstrip("-").isdigit():
            declared_codes.add(int(k))
        else:
            violations.append(f"cli_contract.{k!r}: key must be int (or str-of-int)")
            continue
        if not _nonblank_str(v):
            violations.append(
                f"cli_contract[{k!r}]: value must be non-empty str description"
            )
    missing = EXPECTED_EXIT_CODES - declared_codes
    if missing:
        violations.append(
            f"cli_contract: missing required exit codes {sorted(missing)} "
            f"(must include {sorted(EXPECTED_EXIT_CODES)})"
        )


def _check_cases(value: Any, violations: list[str], expected_name: str | None = None) -> None:
    """cases[] aligned with tests/behavior/fixtures/triggers.yaml schema.
    Per ADR §3.4 + audit a2 #2: ≥5 items + 70/30 mix + required fields per case.

    *expected_name* (the sidecar's `name`) lets us pin per-case identity:
    D11 — every case.expected_skill must equal it; D7 — a skills/-rooted
    skill_file_ref must live under skills/<name>/."""
    if not isinstance(value, list):
        violations.append(f"cases: must be list, got {type(value).__name__}")
        return
    if len(value) < 5:
        violations.append(
            f"cases: must have at least 5 items per GUIDE §7, got {len(value)}"
        )

    desc_count = 0
    explicit_count = 0
    for i, case in enumerate(value):
        if not isinstance(case, dict):
            violations.append(f"cases[{i}]: must be mapping")
            continue
        # required fields (drift_hash retired in M3 / spec §6 — the drift-hash
        # mechanism was fully removed in PR-3, so it is no longer a case field)
        for fld in ("id", "style", "prompt", "expected_skill",
                    "skill_file_ref"):
            if fld not in case:
                violations.append(f"cases[{i}].{fld}: missing required field")
            elif case[fld] is None:  # round-2 verify: present-null required field
                violations.append(f"cases[{i}].{fld}: must not be null")
        # Unknown case keys are intentionally tolerated (forward-compat):
        # this loop checks required fields + known field types; it never
        # rejects extras (forward-compat after the M3 drift_hash removal).
        # id format (D11: a present non-str id slipped past the isinstance guard)
        cid = case.get("id")
        if cid is not None and (not isinstance(cid, str) or not CASE_ID_RE.match(cid)):
            violations.append(
                f"cases[{i}].id: must be a str matching {CASE_ID_RE.pattern}, got {cid!r}"
            )
        # style enum (D10: a list/dict value would raise TypeError on `not in`)
        style = case.get("style")
        if not isinstance(style, str) or style not in ALLOWED_FIXTURE_STYLE:
            violations.append(
                f"cases[{i}].style: must be one of "
                f"{sorted(ALLOWED_FIXTURE_STYLE)}, got {style!r}"
            )
        else:
            if style == "description_based":
                desc_count += 1
            elif style == "explicit_invocation":
                explicit_count += 1
        # prompt non-empty str (D3: blank)
        if not _nonblank_str(case.get("prompt")):
            violations.append(f"cases[{i}].prompt: must be non-empty str")
        # expected_skill non-empty str (D3) + must equal the sidecar name (D11)
        exp = case.get("expected_skill")
        if not _nonblank_str(exp):
            violations.append(f"cases[{i}].expected_skill: must be non-empty str")
        elif expected_name is not None and exp != expected_name:
            violations.append(
                f"cases[{i}].expected_skill: must equal the sidecar name "
                f"{expected_name!r}, got {exp!r}"
            )
        # skill_file_ref project-relative path (D3 blank + D5 control/drive) pinned
        # to skills/<name>/ when skills/-rooted (D7)
        sfr = case.get("skill_file_ref")
        pv = _exec_path_violation(f"cases[{i}].skill_file_ref", sfr)  # f2 shell-safe charset
        if pv:
            violations.append(pv)
        elif expected_name is not None and isinstance(sfr, str):
            canon = _canon_rel(sfr)  # so ./skills/<other>/ can't dodge the pin
            if canon.startswith("skills/") and not canon.startswith(f"skills/{expected_name}/"):
                violations.append(
                    f"cases[{i}].skill_file_ref: must live under skills/{expected_name}/, got {sfr!r}"
                )

    # Mix rule per ADR §4.2: ≥3 description_based + ≥1 explicit_invocation
    if isinstance(value, list) and len(value) >= 5:
        if desc_count < 3:
            violations.append(
                f"cases: must have ≥3 description_based cases per "
                f"GUIDE §7 ~70/30 mix rule, got {desc_count}"
            )
        if explicit_count < 1:
            violations.append(
                f"cases: must have ≥1 explicit_invocation case per "
                f"GUIDE §7 ~70/30 mix rule, got {explicit_count}"
            )


def _check_host_overrides(value: Any, violations: list[str]) -> None:
    """host_overrides = {"claude": [{"anchor": str, "replacement": str}, ...]}.

    Optional field (overlay design, spec §3/§4). Absent → no-op. When present it
    must be a mapping whose only recognized host key is `claude`, mapping to a
    list of {anchor, replacement} string objects. Deep anchor semantics (occurs
    exactly once, no overlap, body-only) are checked by
    _aqg_wrapper_overlay.build_wrapper at regen time against the real source.
    """
    if value is None:
        return
    if not isinstance(value, dict):
        violations.append(
            f"host_overrides: must be mapping, got {type(value).__name__}"
        )
        return
    for host in value:
        if host != "claude":
            violations.append(
                f"host_overrides: unknown host key {host!r} "
                f"(only 'claude' is supported)"
            )
    claude = value.get("claude")
    if claude is None:
        return
    if not isinstance(claude, list):
        violations.append(
            f"host_overrides.claude: must be list, got {type(claude).__name__}"
        )
        return
    for i, item in enumerate(claude):
        if not isinstance(item, dict):
            violations.append(
                f"host_overrides.claude[{i}]: must be object with str "
                f"'anchor' + 'replacement', got {type(item).__name__}"
            )
            continue
        anchor = item.get("anchor")
        repl = item.get("replacement")
        if not _nonblank_str(anchor):
            violations.append(
                f"host_overrides.claude[{i}].anchor: must be non-empty str"
            )
        if not isinstance(repl, str):
            violations.append(
                f"host_overrides.claude[{i}].replacement: must be str"
            )


def _check_trigger_grammar(value: Any, violations: list[str]) -> None:
    """trigger_grammar = mapping with `keywords[]` + `sentence_patterns[]`."""
    if not isinstance(value, dict):
        violations.append(f"trigger_grammar: must be mapping, got {type(value).__name__}")
        return
    kw = value.get("keywords")
    if not isinstance(kw, list) or not kw:
        violations.append("trigger_grammar.keywords: must be non-empty list of str")
    else:
        for i, k in enumerate(kw):
            if not _nonblank_str(k):
                violations.append(f"trigger_grammar.keywords[{i}]: must be non-empty str")
    sp = value.get("sentence_patterns")
    if not isinstance(sp, list):
        violations.append("trigger_grammar.sentence_patterns: must be list")
    else:
        for i, p in enumerate(sp):
            if not _nonblank_str(p):
                violations.append(
                    f"trigger_grammar.sentence_patterns[{i}]: must be non-empty str"
                )


def check_skill_template(record: Mapping[str, Any]) -> SkillTemplateSchemaResult:
    """Schema check of a sidecar manifest. Returns is_safe + violations + warnings."""
    violations: list[str] = []
    warnings: list[str] = []

    if not isinstance(record, Mapping):
        return SkillTemplateSchemaResult(
            is_safe=False,
            violations=(
                f"<root>: must be a mapping, got {type(record).__name__}",
            ),
        )

    # f1 (verify-round): reject lone UTF-16 surrogates anywhere before the
    # field-level checks. utf-8 (every generated file is written utf-8) cannot
    # encode them, so an un-rejected surrogate becomes a generator crash rather
    # than a clean violation.
    _check_no_surrogates("<root>", record, violations)

    # Unknown top-level keys
    for key in record:
        if key not in ALLOWED_TOP_LEVEL:
            violations.append(f"unknown top-level key: {key!r}")

    # Required keys. Round-2 verify (gpt-5.5): a present-but-null required field
    # (`{"name": null}`) is NOT "missing", and the per-field validators below
    # skip None — so null required fields would slip through. Reject null here.
    for key in REQUIRED_TOP_LEVEL:
        if key not in record:
            violations.append(f"missing required field: {key}")
        elif record[key] is None:
            violations.append(f"required field {key} must not be null")

    # skill_template_schema (Q4 default: contract version)
    sv = record.get("skill_template_schema")
    if sv is not None:
        if not _is_strict_int(sv):
            violations.append(
                f"skill_template_schema: must be int, got {type(sv).__name__}"
            )
        elif sv not in SCHEMA_VERSION_ACCEPTED:
            violations.append(
                f"skill_template_schema: {sv} not in {sorted(SCHEMA_VERSION_ACCEPTED)}"
            )

    # name (slug regex)
    name = record.get("name")
    if isinstance(name, str):
        if not SKILL_NAME_RE.match(name):
            violations.append(f"name: must match {SKILL_NAME_RE.pattern}, got {name!r}")
    elif name is not None:
        violations.append(f"name: must be str, got {type(name).__name__}")

    # description: non-empty str (no length cap per ADR §3.1 + a1 audit #6 fix)
    desc = record.get("description")
    if desc is not None:
        if not isinstance(desc, str):
            violations.append(f"description: must be str, got {type(desc).__name__}")
        elif not desc.strip():  # D3: whitespace-only is not "non-empty"
            violations.append("description: must be non-empty str")

    # boundary_class enum (D10: _check_enum guards isinstance before membership)
    _check_enum("boundary_class", record.get("boundary_class"), ALLOWED_BOUNDARY_CLASS, violations)

    # audit_mode_required (optional metadata: the skill's recommended audit
    # depth for callers). Finding D-a: validate the VALUE — an illegal value is
    # a violation — but do NOT emit a blanket advisory warn for every legal
    # value. That warn fired for all 11 skills every run, was non-actionable
    # noise, masked real warnings, and failed --strict pack-wide. Field stays;
    # only the noise is removed.
    _check_enum("audit_mode_required", record.get("audit_mode_required"), ALLOWED_AUDIT_MODE, violations)

    # version (optional, sidecar-only)
    ver = record.get("version")
    if ver is not None and (not isinstance(ver, str) or not ver.strip()):  # D3
        violations.append("version: must be non-empty str if provided")

    # primary_trigger_keywords (optional list)
    if "primary_trigger_keywords" in record:
        _check_str_list(
            "primary_trigger_keywords",
            record["primary_trigger_keywords"],
            violations,
        )

    # trigger_grammar
    if "trigger_grammar" in record:
        _check_trigger_grammar(record["trigger_grammar"], violations)

    # entry_script (project-relative path under scripts/ or skills/<name>/)
    es = record.get("entry_script")
    if es is not None:
        pv = _exec_path_violation("entry_script", es)  # D3/D5 + f2 shell-safe charset
        if pv:
            violations.append(pv)
        else:
            canon = _canon_rel(es)  # so ./skills/<other>/ can't dodge the D7 pin
            if canon.startswith("skills/"):
                # D7: a skills/-rooted entry must belong to THIS skill, not another
                if isinstance(name, str) and not canon.startswith(f"skills/{name}/"):
                    violations.append(
                        "entry_script: a skills/-rooted entry must live under "
                        f"skills/{name}/ (this skill), got {es!r}"
                    )
            elif not canon.startswith("scripts/"):
                violations.append(
                    "entry_script: must live under scripts/ or skills/<name>/"
                )

    # cli_contract
    if "cli_contract" in record:
        _check_cli_contract(record["cli_contract"], violations)

    # output_shape enum (D10)
    _check_enum("output_shape", record.get("output_shape"), ALLOWED_OUTPUT_SHAPES, violations)

    # path lists
    for fld in ("reads_paths", "writes_paths", "forbidden_paths"):
        if fld in record:
            _check_path_list(fld, record[fld], violations)

    # aqg_agent_gating bool
    aag = record.get("aqg_agent_gating")
    if aag is not None and not isinstance(aag, bool):
        violations.append(
            f"aqg_agent_gating: must be bool, got {type(aag).__name__}"
        )

    # owner_only_actions
    if "owner_only_actions" in record:
        _check_str_list("owner_only_actions", record["owner_only_actions"], violations)

    # cases (pass the sidecar name so per-case expected_skill / skill_file_ref
    # can be pinned to this skill — D7 / D11)
    if "cases" in record:
        _check_cases(
            record["cases"], violations,
            expected_name=name if isinstance(name, str) else None,
        )

    # self_test_entrypoint
    ste = record.get("self_test_entrypoint")
    if ste is not None:
        pv = _exec_path_violation("self_test_entrypoint", ste)  # D3/D5 + f2 shell-safe charset
        if pv:
            violations.append(pv)
        elif isinstance(name, str):
            canon = _canon_rel(ste)  # so ./skills/<other>/ can't dodge the D7 pin
            if canon.startswith("skills/") and not canon.startswith(f"skills/{name}/"):
                # D7: a skills/-rooted self-test must belong to THIS skill
                violations.append(
                    "self_test_entrypoint: a skills/-rooted entry must live under "
                    f"skills/{name}/ (this skill), got {ste!r}"
                )

    # fixed_before_next_task_required_when_findings (echoes handoff manifest invariant 4)
    fbf = record.get("fixed_before_next_task_required_when_findings")
    if fbf is not None and not isinstance(fbf, bool):
        violations.append(
            f"fixed_before_next_task_required_when_findings: must be bool, "
            f"got {type(fbf).__name__}"
        )

    # numeric_values_quoted (defends YAML auto-typing per PR-5fg/5h)
    nvq = record.get("numeric_values_quoted")
    if nvq is not None and not isinstance(nvq, bool):
        violations.append(
            f"numeric_values_quoted: must be bool, got {type(nvq).__name__}"
        )

    # wrapper_generated (overlay design): the migration flag. Strict bool —
    # is_managed_skill() only treats the literal True as managed, so a non-bool
    # here would silently read as legacy; flag it as a schema violation instead.
    wg = record.get("wrapper_generated")
    if wg is not None and not isinstance(wg, bool):
        violations.append(
            f"wrapper_generated: must be bool, got {type(wg).__name__}"
        )

    # host_overrides (overlay design): {"claude": [{anchor, replacement}, ...]}.
    # Shape-only here; build_wrapper enforces the anchor semantics (exactly-once,
    # no-overlap, body-only) at regen time against the actual source text.
    _check_host_overrides(record.get("host_overrides"), violations)

    # ===== a3 audit fix #4: cross-field consistency invariants =====
    bc = record.get("boundary_class")
    rp = record.get("reads_paths") if isinstance(record.get("reads_paths"), list) else []
    wp = record.get("writes_paths") if isinstance(record.get("writes_paths"), list) else []
    fp = record.get("forbidden_paths") if isinstance(record.get("forbidden_paths"), list) else []

    # Invariant A: boundary_class == read-only → writes_paths must be empty
    if bc == "read-only" and wp:
        violations.append(
            f"cross-field: boundary_class=read-only requires writes_paths empty, "
            f"got {len(wp)} entries"
        )

    # Invariant B: forbidden_paths must not overlap reads_paths or writes_paths.
    # D12 (round-1): canonicalize (_canon_rel) so `src` and `src/` compare equal.
    # round-2 verify (gpt-5.5): also catch ancestor/descendant overlap — a
    # forbidden DIRECTORY (real sidecars forbid `secrets/`, `production/`) must
    # preclude a read/write of anything under it, not just the exact same path.
    fp_list = [p for p in fp if isinstance(p, str)]
    rp_list = [p for p in rp if isinstance(p, str)]
    wp_list = [p for p in wp if isinstance(p, str)]
    overlap_reads = sorted({
        f"{a} ~ {b}" for a in fp_list for b in rp_list if _paths_overlap(a, b)
    })
    overlap_writes = sorted({
        f"{a} ~ {b}" for a in fp_list for b in wp_list if _paths_overlap(a, b)
    })
    if overlap_reads:
        violations.append(
            f"cross-field: forbidden_paths overlaps reads_paths: {overlap_reads}"
        )
    if overlap_writes:
        violations.append(
            f"cross-field: forbidden_paths overlaps writes_paths: {overlap_writes}"
        )

    # Final safety pass (round-2 verify): escape any lone surrogate that a
    # sidecar-derived value (name / expected_name / a path / a mapping key) may
    # have carried raw into a message above. This single choke point guarantees
    # every returned string is utf-8-encodable, so a caller printing a violation
    # to a strict stderr can never hit a fresh UnicodeEncodeError. is_safe keys
    # off the pre-sanitized list, so escaping never changes the verdict.
    return SkillTemplateSchemaResult(
        is_safe=not violations,
        violations=tuple(_surrogate_safe(v) for v in violations),
        warnings=tuple(_surrogate_safe(w) for w in warnings),
    )


def assert_safe_skill_template(record: Mapping[str, Any]) -> None:
    """Raise SkillTemplateSchemaError if record fails schema check."""
    result = check_skill_template(record)
    if not result.is_safe:
        raise SkillTemplateSchemaError(list(result.violations))
