#!/usr/bin/env python3
"""Skill template validator (Wave 4+ machine-template B-1).

Implements the §4.2 spec. Validator input = sidecar (`skills/<name>/skill.template.json`)
+ skill directory; outputs pass/fail + missing-fields list.

Always-on checks (per ADR §4.2):
- sidecar schema valid (via _skill_template_schema.check_skill_template)
- SKILL.md frontmatter has exactly name + description (no extras)
- SKILL.md contains a Boundaries-related H2 (loose match: boundary/stop/scope)
- triggers.yaml has ≥5 cases for this skill
- skill name in aqg_doctor.py skill-name tuples
- skill opts into wrapper generation (`wrapper_generated: true` in the sidecar)
- skill name in both install.sh files (source + claude pack)
- exit-code contract (0/1/2/3/70) documented in scripts entry docstring or SKILL.md
- agents/openai.yaml present with non-empty interface.display_name (Codex picker
  fallback guard — missing display_name renders the "Aqg <Name>" slug fallback)

Conditional / advisory:
- audit_mode_required → warn-only (Q6 advisory v1)
- _aqg_context.sh source pattern → warn-only (post PR-3b3 will become required)
- description competing-context / pushiness → warn-only (Anthropic skill-creator;
  flags "always use" / "best skill" / "for all tasks" style universal-priority
  phrasing; GUIDE §2.3b)
- wrapper out of sync with source (managed skills) → warn-only; `--strict` fails
  to match the CI regen→git-status gate (reuses aqg_skill_gen.regen_one check)

CLI:
    python3 scripts/aqg_skill_validator.py <skill-name>
    python3 scripts/aqg_skill_validator.py <skill-name> --strict   # fail on warnings
    python3 scripts/aqg_skill_validator.py <skill-name> --json     # JSON output

Exit codes:
    0: success - no violations; advisory warnings allowed unless --strict
    1: violations found in sidecar / skill_dir / cross_cutting (or under strict)
    2: usage error - sidecar missing, skill dir missing, or repo root not found
    3: config_error - reserved for future use (not currently emitted)
    70: internal_error - reserved for future use (not currently emitted)

Requires PyYAML (a DECLARED dependency) to parse triggers.yaml / openai.yaml /
SKILL.md frontmatter. SKILL.md frontmatter + openai.yaml display_name degrade to
a best-effort regex fallback without it, but the triggers-count check
(_count_triggers_for_skill) hard-fails without PyYAML — install it with
`pip install -r requirements.txt` (declares pyyaml). Otherwise stdlib-only.
"""

from __future__ import annotations

import argparse
import ast
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

# Shared migration predicate (overlay design, spec 2026-05-31 §4): a managed
# skill's Claude wrapper is generated by `aqg_skill_gen.py regen` and guarded by
# the CI regen→git-status gate, so the cross-cutting registration requires
# is_managed_skill (the retired test_drift.py hash baseline is gone — spec §6/§7).
# ONE shared helper across regen / validator / check_fixture_mix so they agree.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from _aqg_wrapper_overlay import is_managed_skill  # noqa: E402


EXIT_OK = 0
EXIT_INVALID = 1
EXIT_USAGE = 2

SIDECAR_FILENAME = "skill.template.json"

# a3 audit fix #2: explicit allowlist of accepted boundary-section H2 titles.
# Loose-regex (Owner / Scope) was over-permissive AND under-permissive (existing
# closeout skill uses Workflow / Completion Standard / Final Answer Shape).
# We now require an exact match; missing boundary H2 in skills with
# boundary_class != read-only is a hard violation; read-only skills get advisory.
_ACCEPTED_BOUNDARY_H2 = frozenset({
    "## Boundaries",
    "## Boundary Rules",
    "## Stop Boundaries",
    "## Stop Rules",
})

# Source-line pattern for _aqg_context.sh helper (post PR-3b3 advisory)
_AQG_CONTEXT_SOURCE_RE = re.compile(
    r"source\s+\"?\$?\{?[A-Z_]*ROOT[^\"]*?_aqg_context\.sh"
)

# Frontmatter parser: simple YAML key: value (no nested) — frontmatter must be
# delimited by `---` lines and contain only `name:` and `description:` keys.
_FRONTMATTER_KEY_RE = re.compile(r"^([a-zA-Z_][a-zA-Z0-9_-]*)\s*:\s*(.*?)\s*$")


# ===== Repo root resolution =====


def _find_repo_root(start: Path | None = None) -> Path:
    if start is None:
        start = Path(__file__).resolve().parent
    p = start.resolve()
    for _ in range(10):
        if (p / "VERSION").is_file() and (p / "scripts").is_dir() and (p / "templates").is_dir():
            return p
        if p.parent == p:
            break
        p = p.parent
    raise RuntimeError(
        f"cannot find AQG repo root from {start}; expected VERSION + scripts/ + templates/"
    )


@dataclass(frozen=True)
class SkillValidationResult:
    is_valid: bool
    skill_name: str
    sidecar_violations: tuple[str, ...] = field(default_factory=tuple)
    skill_dir_violations: tuple[str, ...] = field(default_factory=tuple)
    cross_cutting_violations: tuple[str, ...] = field(default_factory=tuple)
    warnings: tuple[str, ...] = field(default_factory=tuple)


# ===== Sidecar load + validate =====


def _load_sidecar(sidecar_path: Path) -> dict | None:
    """Load sidecar JSON; raises on parse error. Returns None if file missing."""
    if not sidecar_path.is_file():
        return None
    try:
        text = sidecar_path.read_text(encoding="utf-8")
        loaded = json.loads(text)
    except (OSError, json.JSONDecodeError) as exc:
        raise RuntimeError(f"failed to load {sidecar_path}: {exc}") from exc
    if not isinstance(loaded, dict):
        raise RuntimeError(
            f"{sidecar_path}: root must be object, got {type(loaded).__name__}"
        )
    return loaded


# ===== SKILL.md frontmatter validation =====


def _parse_frontmatter(skill_md_text: str) -> tuple[dict[str, str], list[str]]:
    """Return (parsed_frontmatter_dict, errors).
    a3 audit fix #5: prefer yaml.safe_load on the frontmatter block (handles
    quoted values, CRLF, folded scalars). Fall back to manual line parsing
    only when PyYAML is unavailable."""
    errors: list[str] = []
    # Normalize CRLF → LF before delimiter check (audit #5 — CRLF tolerance)
    normalized = skill_md_text.replace("\r\n", "\n").replace("\r", "\n")
    if not normalized.startswith("---\n"):
        errors.append("SKILL.md: must start with `---\\n` frontmatter delimiter")
        return {}, errors
    try:
        end = normalized.index("\n---\n", 4)
    except ValueError:
        errors.append("SKILL.md: missing closing `---` frontmatter delimiter")
        return {}, errors

    body = normalized[4:end]
    # Try yaml.safe_load first (handles quoted values, folded scalars, comments)
    try:
        import yaml  # type: ignore[import-untyped]
        loaded = yaml.safe_load(body)
        if isinstance(loaded, dict):
            # Coerce all values to str for comparison; reject non-scalar values
            parsed: dict[str, str] = {}
            for k, v in loaded.items():
                if not isinstance(k, str):
                    errors.append(
                        f"SKILL.md frontmatter: key must be str, got {type(k).__name__}"
                    )
                    continue
                if v is None:
                    parsed[k] = ""
                elif isinstance(v, (str, int, float, bool)):
                    parsed[k] = str(v)
                else:
                    errors.append(
                        f"SKILL.md frontmatter.{k}: value must be scalar, "
                        f"got {type(v).__name__}"
                    )
            return parsed, errors
        # YAML root not dict — fall through to manual parse for clearer error
    except ImportError:
        pass  # fall back to manual
    except Exception as exc:  # noqa: BLE001 — yaml errors are subclasses
        errors.append(f"SKILL.md frontmatter: YAML parse error: {exc}")
        return {}, errors

    # Manual line parsing fallback (PyYAML missing OR yaml-load returned non-dict)
    parsed = {}
    for line in body.splitlines():
        if not line.strip():
            continue
        m = _FRONTMATTER_KEY_RE.match(line)
        if not m:
            errors.append(
                f"SKILL.md frontmatter: cannot parse line {line!r}"
            )
            continue
        key, value = m.group(1), m.group(2)
        if (value.startswith('"') and value.endswith('"')) or \
           (value.startswith("'") and value.endswith("'")):
            value = value[1:-1]
        parsed[key] = value
    return parsed, errors


def _validate_frontmatter(skill_md_path: Path, sidecar: dict[str, Any]) -> list[str]:
    """SKILL.md frontmatter must have EXACTLY name + description, matching sidecar."""
    errors: list[str] = []
    if not skill_md_path.is_file():
        return [f"SKILL.md: missing at {skill_md_path}"]
    try:
        text = skill_md_path.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"SKILL.md: read failed: {exc}"]

    parsed, parse_errs = _parse_frontmatter(text)
    errors.extend(parse_errs)
    if parse_errs:
        return errors

    # Exactly name + description
    extra_keys = set(parsed.keys()) - {"name", "description"}
    if extra_keys:
        errors.append(
            f"SKILL.md frontmatter: must contain only `name` and `description`, "
            f"found extra keys {sorted(extra_keys)}"
        )
    if "name" not in parsed:
        errors.append("SKILL.md frontmatter: missing `name`")
    elif parsed["name"] != sidecar.get("name"):
        errors.append(
            f"SKILL.md frontmatter.name ({parsed['name']!r}) != "
            f"sidecar.name ({sidecar.get('name')!r})"
        )
    if "description" not in parsed:
        errors.append("SKILL.md frontmatter: missing `description`")
    elif parsed["description"] != sidecar.get("description"):
        errors.append(
            f"SKILL.md frontmatter.description differs from sidecar.description"
        )
    return errors


def _validate_boundary_section(
    skill_md_path: Path, boundary_class: str | None
) -> tuple[list[str], list[str]]:
    """a3 audit fix #2: explicit allowlist H2 check.
    Returns (errors, warnings).
    - boundary_class != read-only: missing H2 → hard error
    - boundary_class == read-only: missing H2 → advisory warn only
    """
    if not skill_md_path.is_file():
        return [], []
    try:
        text = skill_md_path.read_text(encoding="utf-8")
    except OSError:
        return [], []
    has_boundary_h2 = any(
        re.search(rf"^{re.escape(h2)}\s*$", text, re.MULTILINE)
        for h2 in _ACCEPTED_BOUNDARY_H2
    )
    if has_boundary_h2:
        return [], []
    msg = (
        f"SKILL.md: missing boundary section H2 (must be one of "
        f"{sorted(_ACCEPTED_BOUNDARY_H2)}); see GUIDE §1 anatomy"
    )
    if boundary_class == "read-only":
        return [], [msg + " — advisory because boundary_class is read-only"]
    return [msg], []


def _check_aqg_context_source(skill_md_path: Path) -> list[str]:
    """Advisory check: SKILL.md should source _aqg_context.sh helper post PR-3b3."""
    if not skill_md_path.is_file():
        return []
    try:
        text = skill_md_path.read_text(encoding="utf-8")
    except OSError:
        return []
    if not _AQG_CONTEXT_SOURCE_RE.search(text):
        return [
            "SKILL.md: does not source `scripts/_aqg_context.sh` helper "
            "(advisory v1; will become required after PR-3b3 mass migration)"
        ]
    return []


# ===== Description competing-context / pushiness (advisory) =====

# Anthropic skill-creator: a description should scope WHEN to use the skill
# (triggers), not claim universal priority. Pushy descriptions dilute the whole
# pack's auto-trigger signal — if every skill shouts "always use me", the model's
# selection gets noisier. These patterns target ABSOLUTE / SUPERLATIVE /
# EXCLUSIVITY phrasing only; the AQG house style "Use PROACTIVELY when …" /
# "Use before …" is scoped guidance and deliberately does NOT match (verified
# against all shipped descriptions — see tests/behavior/test_skill_description_pushiness.py).
_PUSHINESS_PATTERNS: tuple[tuple[str, "re.Pattern[str]"], ...] = (
    ("absolute-frequency", re.compile(
        r"\balways use\b|\bevery single (?:time|task)\b|\bon every (?:task|request|change|commit|edit)\b",
        re.IGNORECASE)),
    ("over-broad-scope", re.compile(
        r"\bfor all (?:tasks?|cases?|situations?|requests?|code|work|changes?)\b"
        r"|\bfor any (?:task|case|situation|request)\b|\bfor everything\b"
        r"|\bin all (?:cases|situations)\b",
        re.IGNORECASE)),
    ("superlative", re.compile(
        r"\b(?:the )?(?:best|most powerful|ultimate|premier|essential|indispensable) "
        r"(?:skill|tool|choice|option|way|reviewer|gate)\b|(?:^|\s)#1 (?:skill|tool)\b|\bsingle best\b",
        re.IGNORECASE)),
    ("exclusivity", re.compile(
        r"\bthe only (?:skill|tool|way|option|reviewer)\b"
        r"|\bnever use (?:any other|anything else|another)\b|\binstead of (?:any |all )?other\b",
        re.IGNORECASE)),
    ("urgency", re.compile(
        r"\byou must always\b|\bmust be used for (?:all|every)\b|\bnever skip\b"
        r"|\bcritical that you use\b",
        re.IGNORECASE)),
)


def _check_description_pushiness(description: str) -> list[str]:
    """Advisory: flag competing-context / pushiness phrasing in a skill
    description (Anthropic skill-creator). A description should scope WHEN to use
    the skill (triggers, e.g. "Use PROACTIVELY when …"), not claim universal
    priority ("always use", "best skill", "for all tasks", "the only tool").

    Advisory only — wording is a judgment call, never a hard violation; the
    result feeds `warnings`. Returns a single advisory string (listing every
    matched category, to avoid flooding) or an empty list. GUIDE §2.3b.
    """
    if not description or not description.strip():
        return []
    hits: list[str] = []
    for label, pattern in _PUSHINESS_PATTERNS:
        m = pattern.search(description)
        if m:
            hits.append(f"{label}: {m.group(0)!r}")
    if not hits:
        return []
    return [
        "description: possible competing-context / pushiness — "
        + "; ".join(hits)
        + ". A description should scope WHEN to use the skill (triggers), not "
        "claim universal priority; pushy wording dilutes the pack's auto-trigger "
        "signal (Anthropic skill-creator; GUIDE §2.3b). Advisory."
    ]


# ===== Codex interface (display_name) =====


def _extract_display_name(openai_yaml_text: str) -> str | None:
    """Return `interface.display_name` from an openai.yaml body, else None.

    Prefer PyYAML (the declared dependency); fall back to a best-effort
    single-line regex on the degraded no-PyYAML path.
    """
    try:
        import yaml  # type: ignore[import-untyped]
        loaded = yaml.safe_load(openai_yaml_text)
        if isinstance(loaded, dict):
            iface = loaded.get("interface")
            if isinstance(iface, dict):
                dn = iface.get("display_name")
                return dn if isinstance(dn, str) else None
        return None
    except ImportError:
        # Degraded no-PyYAML path: best-effort line scan. Strip surrounding
        # quotes and any trailing inline `# comment` so an empty value like
        # `display_name: "" # TODO` reads as empty, not as the comment text
        # (audit 57f41525 — the naive `.strip('"')` falsely passed it).
        m = re.search(
            r"^\s*display_name\s*:\s*(.+?)\s*$", openai_yaml_text, re.MULTILINE
        )
        if not m:
            return None
        raw = m.group(1).strip()
        if raw[:1] in ('"', "'"):
            quote = raw[0]
            close = raw.find(quote, 1)
            value = raw[1:close] if close != -1 else raw[1:]
        else:
            value = raw.split(" #", 1)[0].rstrip()
        return value.strip() or None
    except Exception:  # noqa: BLE001 — malformed YAML → caller treats as missing
        return None


def _validate_codex_interface(skill_dir: Path) -> list[str]:
    """Every AQG skill ships to Codex (all are in CODEX_SKILL_NAMES), so it must
    carry `agents/openai.yaml` with a non-empty `interface.display_name`.

    When it is absent the Codex skill picker falls back to the directory slug
    and renders "Aqg <Name>" — the naming-convention fallback bug (GUIDE §4).
    Hard violation: 4 skills shipped without it before this gate existed.
    """
    openai_yaml = skill_dir / "agents" / "openai.yaml"
    if not openai_yaml.is_file():
        return [
            "agents/openai.yaml: missing — every Codex-distributed skill needs "
            "interface.display_name, else the Codex picker shows the 'Aqg <Name>' "
            "slug fallback (GUIDE §4)"
        ]
    try:
        text = openai_yaml.read_text(encoding="utf-8")
    except OSError as exc:
        return [f"agents/openai.yaml: read failed: {exc}"]
    display_name = _extract_display_name(text)
    if not (display_name and display_name.strip()):
        return [
            "agents/openai.yaml: interface.display_name missing or empty "
            "(needed so the Codex picker shows a real name, not the "
            "'Aqg <Name>' slug fallback)"
        ]
    return []


# ===== Cross-cutting registration =====


def _file_contains_quoted_skill(
    path: Path, skill_name: str, *, strip_shell_comments: bool = False
) -> bool:
    """a3 audit fix #1 + Batch-2 audit C1a: the skill name must be
    QUOTE-delimited (`'name'` / `"name"`) or PATH-delimited (`/name/`,
    `/name"`, `/name'`) — a bare word-boundary match let a commented-out
    (`# aqg-foo`) or prose mention satisfy registration (convergent FALSE-PASS).

    D2: a quote/path mention INSIDE a comment (`# "aqg-foo"`, `# skills/aqg-foo/`)
    still false-passed the quote/path regex. For shell files pass
    strip_shell_comments=True to drop `#` comments before matching (a skill name
    never contains `#`, so a per-line `split('#', 1)[0]` is safe for these
    fixtures). The python doctor registry is checked STRUCTURALLY by
    _doctor_registers_skill (ast) instead of by this regex.

    Accepted real registration form (shell): quoted bash array entry
    `"<name>"`, or a `skills/<name>/` path. Rejected: comment / prose mentions.
    """
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except OSError:
        return False
    if strip_shell_comments:
        text = "\n".join(line.split("#", 1)[0] for line in text.splitlines())
    # Left delimiter must be a quote (' ") or path separator (/); right
    # delimiter likewise a quote or path separator.
    name = re.escape(skill_name)
    pattern = re.compile(rf"""['"/]{name}['"/]""")
    return bool(pattern.search(text))


def _doctor_registers_skill(doctor_path: Path, skill_name: str) -> bool:
    """D2: confirm skill_name is a real member of BOTH CLAUDE_SKILL_NAMES and
    CODEX_SKILL_NAMES in aqg_doctor.py, parsed via ast.

    A commented-out or prose mention (`# "aqg-foo"`) is invisible to the parser,
    so — unlike a quote/path regex over the raw text — it cannot satisfy
    registration. Both module-level tuples must list the name as a string
    constant; a missing/unparseable doctor reads as unregistered (fail-closed).
    """
    if not doctor_path.is_file():
        return False
    try:
        tree = ast.parse(doctor_path.read_text(encoding="utf-8"))
    except (OSError, SyntaxError, ValueError):
        return False
    required = ("CLAUDE_SKILL_NAMES", "CODEX_SKILL_NAMES")
    members: dict[str, set[str]] = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for tgt in node.targets:
            if isinstance(tgt, ast.Name) and tgt.id in required:
                if isinstance(node.value, (ast.Tuple, ast.List)):
                    members[tgt.id] = {
                        e.value
                        for e in node.value.elts
                        if isinstance(e, ast.Constant) and isinstance(e.value, str)
                    }
    return all(skill_name in members.get(name, set()) for name in required)


def _validate_cross_cutting(
    repo_root: Path, skill_name: str, sidecar: dict | None = None
) -> list[str]:
    """Check skill is registered in doctor / install.sh × 2 / triggers.yaml +
    opts into wrapper generation (spec 2026-05-31 §6/§7).

    a3 audit fix #1: use exact-name boundary match (defends against
    substring-of-other-skill false positives).

    wrapper_generated clause (overlay design, spec §6/§7): the legacy
    test_drift.py hash baseline was retired once all skills migrated, so a skill
    MUST opt into wrapper generation (is_managed_skill(sidecar) is True); its
    committed wrapper is then guarded by the CI regen→git-status gate. When
    `sidecar` is None it is loaded from skills/<skill_name>/skill.template.json
    (best-effort; a missing/malformed sidecar reads as unmanaged, so the
    requirement still fails closed). doctor / install.sh × 2 / triggers.yaml ≥5
    are unchanged and always required.
    """
    errors: list[str] = []

    if sidecar is None:
        # Best-effort load; a missing/unparseable sidecar reads as unmanaged
        # (managed=False), failing the wrapper_generated clause (fail-closed).
        try:
            loaded = _load_sidecar(repo_root / "skills" / skill_name / SIDECAR_FILENAME)
        except RuntimeError:
            loaded = None
        sidecar = loaded if isinstance(loaded, dict) else {}
    managed = is_managed_skill(sidecar)

    # doctor: skill name must be a real member of BOTH SKILL_NAMES tuples (D2:
    # ast-parsed by _doctor_registers_skill, so a commented-out / prose mention
    # can't false-pass the way a raw quote/path regex did).
    doctor = repo_root / "scripts" / "aqg_doctor.py"
    if not _doctor_registers_skill(doctor, skill_name):
        errors.append(
            f"scripts/aqg_doctor.py: skill name {skill_name!r} not registered "
            f"(must appear in CLAUDE_SKILL_NAMES + CODEX_SKILL_NAMES)"
        )

    # install scripts (source + claude pack). D2: strip shell `#` comments first
    # so a commented mention can't satisfy registration.
    src_install = repo_root / "scripts" / "install.sh"
    if not _file_contains_quoted_skill(src_install, skill_name, strip_shell_comments=True):
        errors.append(
            f"scripts/install.sh: skill name {skill_name!r} not registered"
        )
    claude_install = repo_root / "agent-packs" / "claude-code" / "install.sh"
    if not _file_contains_quoted_skill(claude_install, skill_name, strip_shell_comments=True):
        errors.append(
            f"agent-packs/claude-code/install.sh: skill name {skill_name!r} not registered"
        )

    # wrapper_generated — overlay regime (spec 2026-05-31 §6/§7). The legacy
    # test_drift.py hash baseline was retired once all skills migrated, so a
    # skill MUST opt into wrapper generation; its committed wrapper is then
    # guarded by the CI regen→git-status gate. Fail-closed (Batch-2 audit C1b):
    # a skill whose sidecar lacks `wrapper_generated: true` is unregistered.
    if not managed:
        errors.append(
            f"skills/{skill_name}/skill.template.json: skill is not managed "
            f"(missing `wrapper_generated: true`); the wrapper is no longer "
            f"drift-hash-gated, so it must opt into regen→git-status generation"
        )

    # triggers.yaml — Batch-2 audit C1b: REQUIRED file (fail-closed). Parse YAML
    # and count `expected_skill: <name>` exact matches.
    triggers = repo_root / "tests" / "behavior" / "fixtures" / "triggers.yaml"
    if not triggers.is_file():
        errors.append(
            "tests/behavior/fixtures/triggers.yaml: required triggers fixture missing"
        )
    else:
        count = _count_triggers_for_skill(triggers, skill_name)
        if count is None:
            errors.append(
                "tests/behavior/fixtures/triggers.yaml: failed to parse — PyYAML "
                "is a required dependency (pip install -r requirements.txt), or the file has a "
                "YAML syntax error"
            )
        elif count < 5:
            errors.append(
                f"tests/behavior/fixtures/triggers.yaml: skill {skill_name!r} "
                f"has {count} cases, must have at least 5 per GUIDE §7"
            )

    return errors


def _count_triggers_for_skill(triggers_path: Path, skill_name: str) -> int | None:
    """Parse triggers.yaml and count cases where expected_skill == skill_name.
    Returns None if YAML loader unavailable / parse fails (caller treats as error).
    """
    try:
        import yaml  # type: ignore[import-untyped]
    except ImportError:
        return None
    try:
        text = triggers_path.read_text(encoding="utf-8")
        loaded = yaml.safe_load(text)
    except Exception:  # noqa: BLE001 — yaml.YAMLError + OSError both subclass Exception
        return None
    # Batch-2 audit P2: count only the documented fixture container — a
    # top-level list, OR the value under an explicit `cases` key. The old code
    # extended `cases` with EVERY top-level list value, so an archived/unrelated
    # list with matching `expected_skill` could satisfy the >=5 minimum.
    cases: list[Any] = []
    if isinstance(loaded, list):
        cases = loaded
    elif isinstance(loaded, dict):
        container = loaded.get("cases")
        if isinstance(container, list):
            cases = container
    count = 0
    for c in cases:
        if isinstance(c, dict) and c.get("expected_skill") == skill_name:
            count += 1
    return count


# ===== Wrapper-sync (generated-artifact drift) =====


def _check_wrapper_sync(
    repo_root: Path, skill_name: str, sidecar: dict | None
) -> list[str]:
    """Advisory (warn; `--strict` fails, matching the CI regen→git-status gate):
    a managed skill's committed Claude wrapper must equal a fresh render from
    source. Editing the source SKILL.md without re-running `regen --all` leaves
    the wrapper stale — the static checks above all pass yet CI's wrapper-sync
    gate fails. This closes that local gap.

    Read-only: it NEVER regenerates (calls regen_one with check=True). Reuses
    `aqg_skill_gen.regen_one` — the SAME pure build_wrapper core that
    `regen --all` and the CI gate use — so the three can never disagree about
    drift. Unmanaged skills have no wrapper → skip (their `managed` cross-cutting
    violation already fires). Any failure (bad anchor, missing/unreadable/binary
    file, import) surfaces as one advisory line, never a crash — the validator
    runs over EVERY skill, so one bad skill must not abort the batch.
    """
    if not is_managed_skill(sidecar):
        return []  # unmanaged: the source IS the only file; no wrapper to sync
    try:
        from aqg_skill_gen import regen_one  # noqa: E402 — lazy; sibling script
    except ImportError as exc:
        return [f"wrapper-sync: cannot import aqg_skill_gen ({exc}); check skipped"]
    try:
        diff = regen_one(repo_root, skill_name, check=True)
    except Exception as exc:  # noqa: BLE001 — never abort the batch over one skill
        # regen_one raises RuntimeError on a bad anchor / missing source, but its
        # source/wrapper read_text can also surface OSError / UnicodeDecodeError on
        # an unreadable or binary file — none of which may crash the per-skill run
        # (audit b00eb16e f1, convergent 3/3).
        return [f"wrapper-sync: could not verify wrapper for {skill_name!r}: {exc}"]
    if diff:
        return [
            f"agent-packs/claude-code/skills/{skill_name}/SKILL.md: wrapper OUT OF "
            f"SYNC with source — run `python3 scripts/aqg_skill_gen.py regen --all` "
            f"and commit (CI regen→git-status gate hard-fails on this; `--strict` "
            f"fails here to match)"
        ]
    return []


# ===== Exit-code contract documentation =====


_MAX_ENTRY_SCAN_BYTES = 1 << 20  # 1 MiB. An entry skeleton is a few KB; cap the
# read so a schema-bypassed oversized / device entry_script can't OOM the scan (D9).


def _top_comment_block(text: str) -> str:
    """D13: the top-of-file `#`-comment region (after an optional shebang) of a
    non-python entry script — where a `#`-style exit-code contract lives. Scans
    until the FIRST non-comment, non-blank CODE line, so an incidental `0: ...`
    deep in the script body can't false-pass the contract (the old code scanned
    the WHOLE file).

    Blank lines inside the region are skipped, NOT treated as the end (audit f2):
    a contract often sits in a second comment paragraph
    (`# header` / blank / `# Exit codes:` / `# 0: ok` ...). Only the first line
    of real code terminates the region.
    """
    block: list[str] = []
    for i, line in enumerate(text.splitlines()):
        s = line.strip()
        if i == 0 and s.startswith("#!"):
            continue  # shebang
        if not s:
            continue  # blank line: skip, but do NOT end the region (f2)
        if s.startswith("#"):
            block.append(line)
        else:
            break  # first real code line ends the top-of-file comment region
    return "\n".join(block)


def _check_exit_code_documentation(
    repo_root: Path, sidecar: dict[str, Any]
) -> list[str]:
    """a3 audit fix #3: check the 0/1/2/3/70 contract is documented inside the
    entry script's MODULE DOCSTRING (python, via ast.get_docstring) or its
    top-of-file comment block (non-python, D13) — not in arbitrary code/prose.

    D9 belt: a schema-invalid sidecar is normally stopped earlier by
    validate_skill, but resolve()-containment + is_file + a size cap here are
    defense-in-depth so a malicious entry_script (`../../dev/...`, an absolute
    path, or an oversized file) can never be read into memory by this scan.
    """
    errors: list[str] = []
    entry = sidecar.get("entry_script")
    if not isinstance(entry, str):
        return []
    entry_path = repo_root / entry
    # D9: containment — refuse to read anything resolving outside repo_root.
    repo_resolved = repo_root.resolve()
    try:
        resolved = entry_path.resolve()
    except (OSError, RuntimeError) as exc:
        # audit f1: pathlib raises RuntimeError (not OSError) on a symlink loop —
        # a committed self-referential symlink entry_script must return a
        # controlled violation here, not crash the CI validator.
        errors.append(f"entry_script {entry!r}: cannot resolve: {exc}")
        return errors
    if resolved != repo_resolved and repo_resolved not in resolved.parents:
        errors.append(f"entry_script {entry!r}: resolves outside repo root")
        return errors
    if not entry_path.is_file():
        errors.append(f"entry_script {entry!r}: file not found")
        return errors
    # D9: size cap — refuse to slurp a huge file (an entry skeleton is a few KB).
    try:
        size = entry_path.stat().st_size
    except OSError as exc:
        errors.append(f"entry_script {entry!r}: stat failed: {exc}")
        return errors
    if size > _MAX_ENTRY_SCAN_BYTES:
        errors.append(
            f"entry_script {entry!r}: too large to scan "
            f"({size} bytes > {_MAX_ENTRY_SCAN_BYTES})"
        )
        return errors
    try:
        entry_text = entry_path.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError) as exc:
        # UnicodeDecodeError is a ValueError, NOT an OSError: a schema-valid
        # entry_script path (the schema constrains the path shape/location, not
        # the target file's byte encoding) can point at a binary / malformed-
        # UTF-8 file. Catch it so a bad-bytes entry returns a controlled
        # violation instead of crashing the CI validator (verification-round f1,
        # same DoS class as the symlink-loop resolve() guard above).
        errors.append(f"entry_script {entry!r}: read/decode failed: {exc}")
        return errors
    if not entry.endswith(".py"):
        # Non-Python entry (D13): only the top-of-file comment block counts, not
        # the whole body (an incidental `0: x` in a case branch must not pass).
        if not _has_exit_code_block(_top_comment_block(entry_text)):
            errors.append(
                f"entry_script {entry!r}: exit-code contract block "
                f"(0/1/2/3/70) not documented in the top-of-file comment block"
            )
        return errors
    try:
        tree = ast.parse(entry_text)
    except (SyntaxError, ValueError) as exc:
        errors.append(f"entry_script {entry!r}: syntax error: {exc}")
        return errors
    docstring = ast.get_docstring(tree) or ""
    if not _has_exit_code_block(docstring):
        errors.append(
            f"entry_script {entry!r}: module docstring missing exit-code "
            f"contract for 0/1/2/3/70 (must list each code with description)"
        )
    return errors


def _load_entry_ast(repo_root: Path, sidecar: dict[str, Any]) -> ast.Module | None:
    """Safely parse a Python entry_script into an AST for advisory drift checks.

    Mirrors _check_exit_code_documentation's defensive read (resolve-containment,
    is_file, size cap, decode guard) but is SILENT on any failure: drift checks
    are advisory, and the exit-code check already hard-errors a malformed /
    oversized / out-of-tree entry_script. Returns None for non-Python entries or
    any read / parse failure.

    SYNC NOTE (audit 422a3e5f f3): the resolve-containment + size-cap + decode
    guard here duplicate _check_exit_code_documentation's security boundary by
    design — the two differ only in error policy (silent None vs hard error). If
    you harden the containment / size guard in either, mirror it in the other.
    """
    entry = sidecar.get("entry_script")
    if not isinstance(entry, str) or not entry.endswith(".py"):
        return None
    entry_path = repo_root / entry
    repo_resolved = repo_root.resolve()
    try:
        resolved = entry_path.resolve()
    except (OSError, RuntimeError):
        return None
    if resolved != repo_resolved and repo_resolved not in resolved.parents:
        return None
    if not entry_path.is_file():
        return None
    try:
        if entry_path.stat().st_size > _MAX_ENTRY_SCAN_BYTES:
            return None
        return ast.parse(entry_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, SyntaxError, ValueError):
        return None


def _entry_gates_json_flag(tree: ast.Module) -> bool:
    """True if the entry_script reads `args.json` anywhere — a signal that JSON
    output is gated behind an opt-in --json flag (so json is NOT the default).

    Intentionally narrow (audit 422a3e5f f2): only the literal `args.json`
    attribute form is matched. Other json-gating idioms (args.format=='json',
    getattr(args,'json'), or a non-`args` namespace like opts.json) are NOT
    detected — a False result is therefore not proof that no json-gating exists.
    """
    for node in ast.walk(tree):
        if (
            isinstance(node, ast.Attribute)
            and node.attr == "json"
            and isinstance(node.value, ast.Name)
            and node.value.id == "args"
        ):
            return True
    return False


def _check_output_shape_drift(repo_root: Path, sidecar: dict[str, Any]) -> list[str]:
    """Advisory (GUIDE §6.1): output_shape must be the entry_script's DEFAULT
    stdout shape. If output_shape=="json" yet the script gates JSON behind an
    `args.json` (--json) flag, the default output is not json — a drift the
    sidecar should not claim. Silent for any other shape or unreadable entry.
    """
    if sidecar.get("output_shape") != "json":
        return []
    tree = _load_entry_ast(repo_root, sidecar)
    if tree is None:
        return []
    if _entry_gates_json_flag(tree):
        return [
            "output_shape: declares 'json' but entry_script reads `args.json` — "
            "this USUALLY means JSON is gated behind an opt-in --json flag, so the "
            "DEFAULT stdout shape would not be json; verify output_shape reflects "
            "the default per GUIDE §6.1 (heuristic: only the `args.json` form is "
            "matched, so a clean result is not proof that no json-gating exists)"
        ]
    return []


def _has_exit_code_block(text: str) -> bool:
    """Heuristic: text must mention each of 0/1/2/3/70 with a description.

    Batch-2 audit C2: the old regex demanded each code at line-start (bare)
    followed by a delimiter and a 3+ char first token, which FALSE-FAILED
    legitimate documentation:
      (i)   shell entry scripts documenting codes in `#` comments (`# 0: success`)
      (ii)  markdown-table rows (`| 0 | success |`)
      (iii) short descriptions (`0: OK` — "OK" is 2 chars)
    Fix: tolerate a leading comment / pipe / whitespace prefix before the code,
    accept a pipe `|` as a (table) delimiter, and relax the description to any
    non-empty text (`\\S+`). The all-codes-required gate is unchanged.
    """
    if not text:
        return False
    for code in ("0", "1", "2", "3", "70"):
        pattern = re.compile(
            rf"^[#|\s]*{code}\b\s*[:\-—–|]\s*\S+",
            re.MULTILINE,
        )
        if not pattern.search(text):
            return False
    return True


# ===== Main API =====


def validate_skill(
    skill_name: str,
    *,
    repo_root: Path | None = None,
) -> SkillValidationResult:
    """Validate a skill by name. Returns result with is_valid + categorized errors."""
    if repo_root is None:
        repo_root = _find_repo_root()

    skill_dir = repo_root / "skills" / skill_name
    sidecar_path = skill_dir / SIDECAR_FILENAME
    skill_md = skill_dir / "SKILL.md"

    sidecar_violations: list[str] = []
    skill_dir_violations: list[str] = []
    cross_cutting_violations: list[str] = []
    warnings: list[str] = []

    # === Sidecar load + schema check ===
    if not skill_dir.is_dir():
        return SkillValidationResult(
            is_valid=False,
            skill_name=skill_name,
            skill_dir_violations=(f"skills/{skill_name}/: directory does not exist",),
        )
    try:
        sidecar = _load_sidecar(sidecar_path)
    except RuntimeError as exc:
        return SkillValidationResult(
            is_valid=False,
            skill_name=skill_name,
            sidecar_violations=(str(exc),),
        )

    if sidecar is None:
        sidecar_violations.append(
            f"skills/{skill_name}/{SIDECAR_FILENAME}: sidecar manifest missing"
        )
        sidecar = {}  # downstream checks see empty mapping

    # Lazy-import schema module
    sys.path.insert(0, str(repo_root / "scripts"))
    from _skill_template_schema import check_skill_template  # noqa: E402

    schema_result = check_skill_template(sidecar)
    sidecar_violations.extend(schema_result.violations)
    warnings.extend(schema_result.warnings)

    # D9: a schema-invalid sidecar is untrusted — entry_script / path fields may
    # be malicious (../, absolute, oversized). Stop here so those values never
    # flow into the later filesystem reads (_check_exit_code_documentation; the
    # cross-cutting registration reads). The containment + size cap inside
    # _check_exit_code_documentation is the second layer for any direct caller.
    if not schema_result.is_safe:
        return SkillValidationResult(
            is_valid=False,
            skill_name=skill_name,
            sidecar_violations=tuple(sidecar_violations),
            warnings=tuple(warnings),
        )

    # Cross-check sidecar.name matches dir name
    if sidecar.get("name") != skill_name:
        sidecar_violations.append(
            f"sidecar.name ({sidecar.get('name')!r}) != "
            f"skill directory name ({skill_name!r})"
        )

    # === SKILL.md frontmatter ===
    skill_dir_violations.extend(_validate_frontmatter(skill_md, sidecar))
    bc_for_section = sidecar.get("boundary_class") if isinstance(sidecar, dict) else None
    bsec_errors, bsec_warnings = _validate_boundary_section(skill_md, bc_for_section)
    skill_dir_violations.extend(bsec_errors)
    warnings.extend(bsec_warnings)

    # _aqg_context.sh source — advisory only (warn)
    warnings.extend(_check_aqg_context_source(skill_md))

    # Description competing-context / pushiness — advisory only (GUIDE §2.3b).
    # Read from the sidecar, the canonical description the frontmatter is checked
    # against above; a non-str / missing description simply yields no advisory.
    desc = sidecar.get("description") if isinstance(sidecar, dict) else None
    if isinstance(desc, str):
        warnings.extend(_check_description_pushiness(desc))

    # Sidecar output_shape drift — advisory (GUIDE §6.1): output_shape must be the
    # entry_script's DEFAULT stdout shape, not an opt-in (--json) flag's shape.
    warnings.extend(_check_output_shape_drift(repo_root, sidecar))

    # Codex interface display_name — fallback-bug guard (hard)
    skill_dir_violations.extend(_validate_codex_interface(skill_dir))

    # === Cross-cutting registration ===
    # Thread the already-parsed sidecar so the wrapper-generated clause
    # (managed ⇒ regen→git-status gated) decision uses the same dict the schema
    # check ran on, rather than re-reading from disk (spec §6/§7).
    cross_cutting_violations.extend(
        _validate_cross_cutting(repo_root, skill_name, sidecar=sidecar)
    )

    # Wrapper-sync drift (advisory; --strict fails, matching the CI
    # regen→git-status gate). Managed skills only; reuses regen_one(check=True).
    warnings.extend(_check_wrapper_sync(repo_root, skill_name, sidecar))

    # === Cross-check sidecar.cases[].expected_skill consistency ===
    cases = sidecar.get("cases")
    if isinstance(cases, list):
        for i, case in enumerate(cases):
            if isinstance(case, dict):
                exp = case.get("expected_skill")
                if isinstance(exp, str) and exp != skill_name:
                    sidecar_violations.append(
                        f"cases[{i}].expected_skill ({exp!r}) != skill_name ({skill_name!r})"
                    )

    # === Exit-code contract documentation ===
    skill_dir_violations.extend(_check_exit_code_documentation(repo_root, sidecar))

    is_valid = not (
        sidecar_violations or skill_dir_violations or cross_cutting_violations
    )
    return SkillValidationResult(
        is_valid=is_valid,
        skill_name=skill_name,
        sidecar_violations=tuple(sidecar_violations),
        skill_dir_violations=tuple(skill_dir_violations),
        cross_cutting_violations=tuple(cross_cutting_violations),
        warnings=tuple(warnings),
    )


# ===== CLI =====


def _format_human(result: SkillValidationResult, *, strict: bool) -> str:
    lines: list[str] = []
    if result.is_valid and (not strict or not result.warnings):
        lines.append(f"OK: {result.skill_name} valid")
        if result.warnings:
            lines.append(f"  warnings ({len(result.warnings)}):")
            for w in result.warnings:
                lines.append(f"    - {w}")
        return "\n".join(lines)

    lines.append(f"FAIL: {result.skill_name} invalid")
    for label, items in (
        ("sidecar", result.sidecar_violations),
        ("skill_dir", result.skill_dir_violations),
        ("cross_cutting", result.cross_cutting_violations),
    ):
        if items:
            lines.append(f"  {label}:")
            for it in items:
                lines.append(f"    - {it}")
    if result.warnings:
        lines.append(f"  warnings ({len(result.warnings)}):")
        for w in result.warnings:
            lines.append(f"    - {w}")
    return "\n".join(lines)


def _format_json(result: SkillValidationResult) -> str:
    return json.dumps({
        "skill_name": result.skill_name,
        "is_valid": result.is_valid,
        "sidecar_violations": list(result.sidecar_violations),
        "skill_dir_violations": list(result.skill_dir_violations),
        "cross_cutting_violations": list(result.cross_cutting_violations),
        "warnings": list(result.warnings),
    }, indent=2)


# ===== Quality-judge emit (Tier 3-9: LLM-judge SKILL.md description quality) =====
# The static checks above enforce a non-empty description + structure, but the
# §2 four-element description GRAMMAR (lead verb / user-vocab triggers / boundary
# clause / no competing-context) is a JUDGMENT a regex cannot make — GUIDE §2.3b
# names it "a larger evaluation worth a separate pass". This EMITS (does not run)
# a judge prompt, mirroring the aqg-multi-review / phase-transition emit-only
# boundary: the skill never calls an LLM; the caller (Claude / Owner / EAF) runs
# de_audit with the payload and adjudicates per aqg-audit-adjudication.

QUALITY_JUDGE_RUBRIC: dict[str, str] = {
    "lead_verb": (
        "Does the description START with an action verb that mirrors what a user "
        "would naturally TYPE when they want this skill (e.g. Verify / Run / "
        "Decide / Close)? Reject a noun phrase or a 'This skill…' opener. "
        "(GUIDE §2.1)"
    ),
    "trigger_conditions": (
        "Does it name specific surfaces/situations to fire on, in the USER's "
        "vocabulary (words a user actually types), NOT internal AQG jargon? This "
        "is the single biggest determinant of auto-trigger accuracy. (GUIDE §2.2)"
    ),
    "boundary_clause": (
        "Does it state when NOT to fire (e.g. 'not for repeated mid-session "
        "checks', 'not after audit/review returns')? A broad lead verb with no "
        "boundary fires too often and dilutes the whole pack. (GUIDE §2.3)"
    ),
    "no_competing_context": (
        "Is it FREE of pushiness — absolute-frequency ('always use', 'on every "
        "commit'), over-broad-scope ('for all tasks'), superlative ('the best'), "
        "exclusivity ('the only tool')? Scoping a trigger ('Use when…') is good; "
        "claiming priority over other skills is bad. (GUIDE §2.3b)"
    ),
}


def build_quality_judge_prompt(
    skill_name: str,
    *,
    repo_root: Path | None = None,
) -> dict:
    """Build (do NOT run) an LLM-judge prompt scoring a skill's description
    against the §2 four-element grammar. Emit-only: returns a payload the caller
    feeds to de_audit; this function never calls an LLM (mirrors the
    aqg-multi-review / phase-transition emit-only boundary).

    On a missing skill / SKILL.md / description the payload carries a non-null
    `error` and an empty `description`, so the caller fails loudly rather than
    judging nothing. The rubric is always present for a stable payload shape.

    The description is read DIRECTLY from the SKILL.md frontmatter (the artifact
    `skill_md_path` points at), via the same `_parse_frontmatter` the static
    validator uses — NOT from the sidecar. `--quality-judge` skips static
    validation (which is what enforces sidecar == frontmatter), so reading the
    frontmatter directly keeps the judged text authoritative even if the sidecar
    has drifted (audit 529d5d41 f1).
    """
    if repo_root is None:
        repo_root = _find_repo_root()
    skill_md_rel = f"skills/{skill_name}/SKILL.md"
    skill_md = repo_root / "skills" / skill_name / "SKILL.md"

    error: str | None = None
    description = ""
    if not skill_md.is_file():
        error = f"{skill_md_rel}: SKILL.md not found"
    else:
        try:
            text = skill_md.read_text(encoding="utf-8")
        except OSError as exc:
            error = f"{skill_md_rel}: read failed: {exc}"
            text = ""
        if error is None:
            parsed, parse_errs = _parse_frontmatter(text)
            if parse_errs:
                error = f"{skill_md_rel}: frontmatter parse error: {parse_errs[0]}"
            else:
                desc = parsed.get("description")
                if isinstance(desc, str) and desc.strip():
                    description = desc.strip()
                else:
                    error = f"{skill_md_rel}: frontmatter description missing or empty"

    return {
        "skill": skill_name,
        "skill_md_path": skill_md_rel,
        "description": description,
        "description_source": "SKILL.md frontmatter",
        "rubric": dict(QUALITY_JUDGE_RUBRIC),
        "judge_instruction": (
            "Judge ONLY the description text above against each rubric element. "
            "For each element return a verdict (pass | weak | fail) + a one-line "
            "reason citing the description; for weak/fail propose a concrete "
            "one-line rewrite. Do not judge the skill's body or behavior."
        ),
        "output_schema": {
            element: "pass|weak|fail — <reason> — rewrite: <one line or n/a>"
            for element in QUALITY_JUDGE_RUBRIC
        },
        "how_to_run": (
            "emit-only — the validator does NOT call an LLM. Run via "
            "/audit artifact=<description> context=<rubric + judge_instruction> "
            "focus=completeness mode=standard; adjudicate the verdict per "
            "aqg-audit-adjudication. Advisory quality signal, never a hard CI gate "
            "(description wording is a judgment call — GUIDE §2.3b)."
        ),
        "error": error,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="aqg_skill_validator",
        description="Validate an AQG skill against its sidecar manifest + cross-cutting registration.",
    )
    parser.add_argument("skill_name", help="skill directory name (e.g. aqg-startup-preflight)")
    parser.add_argument(
        "--strict",
        action="store_true",
        help="treat warnings as failures",
    )
    parser.add_argument(
        "--json",
        action="store_true",
        help="output result as JSON",
    )
    parser.add_argument(
        "--quality-judge",
        action="store_true",
        help="emit (do NOT run) an LLM-judge prompt scoring the description "
             "against the §2 four-element grammar; feed it to /audit yourself",
    )
    args = parser.parse_args(argv)

    if args.quality_judge:
        # Emit-only: print the judge payload (JSON) and exit; never run an LLM
        # or the static validation. exit 2 if the description could not be read.
        try:
            payload = build_quality_judge_prompt(args.skill_name)
        except RuntimeError as exc:
            print(f"ERROR: {exc}", file=sys.stderr)
            return EXIT_USAGE
        print(json.dumps(payload, indent=2))
        return EXIT_USAGE if payload.get("error") else EXIT_OK

    try:
        result = validate_skill(args.skill_name)
    except RuntimeError as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return EXIT_USAGE

    if args.json:
        print(_format_json(result))
    else:
        print(_format_human(result, strict=args.strict))

    if not result.is_valid:
        return EXIT_INVALID
    if args.strict and result.warnings:
        return EXIT_INVALID
    return EXIT_OK


if __name__ == "__main__":
    raise SystemExit(main())
